In [2]:
import numpy as np
import pandas as pd

In [3]:
x = np.array([[1,2], [3,4], [5,6]])

In [13]:
print("Array : \n", x)
print("Shape : \n", x.shape)
print("Transpose: \n", x.T)
print("Matrix Multiplication : \n", x@x.T)
print("Matrix Multiplication (Old way): \n", np.dot(x,x.T))
print("Mean of each column : \n", x.mean(axis=0))
print("Mean of each row : \n", x.mean(axis = 1))
print("Random matrix (rows, columns) : \n", np.random.randn(3, 3, 2))

Array : 
 [[1 2]
 [3 4]
 [5 6]]
Shape : 
 (3, 2)
Transpose: 
 [[1 3 5]
 [2 4 6]]
Matrix Multiplication : 
 [[ 5 11 17]
 [11 25 39]
 [17 39 61]]
Matrix Multiplication (Old way): 
 [[ 5 11 17]
 [11 25 39]
 [17 39 61]]
Mean of each column : 
 [3. 4.]
Mean of each row : 
 [1.5 3.5 5.5]
Random matrix (rows, columns) : 
 [[[ 1.58136125 -0.03054801]
  [-1.19376087  0.73436938]
  [ 1.54892071  0.91668903]]

 [[-0.89425804  0.44062803]
  [ 0.39946611  1.01551643]
  [ 0.30590424 -0.55861519]]

 [[ 0.83062334  1.29750878]
  [ 1.10269665 -0.46848951]
  [ 1.46347238 -0.31243717]]]


In [3]:
Y = np.random.randn(5,2)
print("Vector : \n", Y)
y_1 = Y.flatten()
print("Flattened Vector : \n", y_1)

Vector : 
 [[-0.40688264  0.5370972 ]
 [-0.67578828  2.00503304]
 [-0.88541057 -1.32912716]
 [-1.05651576  0.39886632]
 [-0.31405287  0.94840912]]
Flattened Vector : 
 [-0.40688264  0.5370972  -0.67578828  2.00503304 -0.88541057 -1.32912716
 -1.05651576  0.39886632 -0.31405287  0.94840912]


In [4]:
print(y_1+(np.random.randn(10)*10))

[-9.56011199e+00  3.91308258e+00  7.21113352e+00 -3.61915450e-01
  5.22590658e+00 -1.77445944e-02  1.39680952e+00 -8.94633885e-01
  7.11274081e+00  1.90552585e+01]


In [5]:
wt = 0.1
bias = 1
lr = 0.2

In [7]:
for epoch in range(5):
    y_pred = wt*y_1 + bias
    error = y_pred - Y
    loss = (error**2).mean()

ValueError: operands could not be broadcast together with shapes (10,) (5,2) 