In [2]:
import numpy as np
import pandas as pd

In [3]:
x = np.array([[1,2], [3,4], [5,6]])

In [13]:
print("Array : \n", x)
print("Shape : \n", x.shape)
print("Transpose: \n", x.T)
print("Matrix Multiplication : \n", x@x.T)
print("Matrix Multiplication (Old way): \n", np.dot(x,x.T))
print("Mean of each column : \n", x.mean(axis=0))
print("Mean of each row : \n", x.mean(axis = 1))
print("Random matrix (rows, columns) : \n", np.random.randn(3, 3, 2))

Array : 
 [[1 2]
 [3 4]
 [5 6]]
Shape : 
 (3, 2)
Transpose: 
 [[1 3 5]
 [2 4 6]]
Matrix Multiplication : 
 [[ 5 11 17]
 [11 25 39]
 [17 39 61]]
Matrix Multiplication (Old way): 
 [[ 5 11 17]
 [11 25 39]
 [17 39 61]]
Mean of each column : 
 [3. 4.]
Mean of each row : 
 [1.5 3.5 5.5]
Random matrix (rows, columns) : 
 [[[ 1.58136125 -0.03054801]
  [-1.19376087  0.73436938]
  [ 1.54892071  0.91668903]]

 [[-0.89425804  0.44062803]
  [ 0.39946611  1.01551643]
  [ 0.30590424 -0.55861519]]

 [[ 0.83062334  1.29750878]
  [ 1.10269665 -0.46848951]
  [ 1.46347238 -0.31243717]]]


In [19]:
Y = np.random.randn(5,2)
print("Vector : \n", Y)
y_1 = Y.flatten()
print("Flattened Vector : \n", y_1)

Vector : 
 [[ 0.41683918  1.7979152 ]
 [-0.04508592  0.28582743]
 [ 1.39774315  0.2875088 ]
 [ 1.03380525 -1.69044828]
 [-0.0988737  -0.77023204]]
Flattened Vector : 
 [ 0.41683918  1.7979152  -0.04508592  0.28582743  1.39774315  0.2875088
  1.03380525 -1.69044828 -0.0988737  -0.77023204]


In [22]:
print(y_1+(np.random.randn(10)*10))

[ -3.32458808  -3.05511861  -1.85929937  -9.30093233 -10.20014518
  15.60574043 -18.65690516  -4.42682606   3.01190998   3.180821  ]
